using FromFromptToFE.DTOs.GitHub;
using FromFromptToFE.Repositories;
using FromFromptToFE.Repositories.Interfaces;
using FromFromptToFE.Services.Interfaces;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace FromFromptToFE.Services
{
    public class GitHubPushService : IGitHubPushService
    {
        private readonly IUserRepository _userRepo;
        private readonly IProjectOutputRepository _outputRepo;

        public GitHubPushService(IUserRepository userRepo, IProjectOutputRepository outputRepo)
        {
            _userRepo = userRepo;
            _outputRepo = outputRepo;
        }

        public async Task<PushResultDto> PushToGitHubAsync(Guid userId, PushToGitHubDto dto)
        {
            var user = await _userRepo.GetByIdAsync(userId)
                ?? throw new Exception("User not found.");

            if (string.IsNullOrWhiteSpace(user.GitHubAccessToken))
                throw new Exception("GitHub account not connected or access token missing. Please reconnect your GitHub account.");

            using var http = new HttpClient();
            http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", user.GitHubAccessToken);
            http.DefaultRequestHeaders.Add("User-Agent", "FromPromptToFE");
            http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/vnd.github+json"));
            http.DefaultRequestHeaders.Add("X-GitHub-Api-Version", "2022-11-28");

            // Step 1: Get GitHub authenticated user's login
            var meRes = await http.GetAsync("https://api.github.com/user");
            if (!meRes.IsSuccessStatusCode)
            {
                var errBody = await meRes.Content.ReadAsStringAsync();
                throw new Exception($"Failed to get GitHub user info (token may be expired). Please reconnect GitHub. Detail: {errBody}");
            }
            var meJson = JsonDocument.Parse(await meRes.Content.ReadAsStringAsync()).RootElement;
            var ownerLogin = meJson.GetProperty("login").GetString()
                ?? throw new Exception("Could not read GitHub login.");

            // Step 2: Create repo if it doesn't exist
            var repoCheckRes = await http.GetAsync($"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}");
            if (!repoCheckRes.IsSuccessStatusCode)
            {
                // Create new repo
                var createBody = JsonSerializer.Serialize(new
                {
                    name = dto.RepoName,
                    description = "Generated by AI Code Gen",
                    @private = false,
                    auto_init = false
                });
                var createRes = await http.PostAsync(
                    "https://api.github.com/user/repos",
                    new StringContent(createBody, Encoding.UTF8, "application/json")
                );
                if (!createRes.IsSuccessStatusCode)
                {
                    var errBody = await createRes.Content.ReadAsStringAsync();
                    throw new Exception($"Failed to create GitHub repository: {errBody}");
                }

                // Wait briefly for GitHub to initialize the repo
                await Task.Delay(1500);
            }

            // Step 3: Get latest project output with generated code
            var outputs = await _outputRepo.GetAllByProjectIdAsync(dto.ProjectId);
            var latest = outputs
                .Where(o => !string.IsNullOrWhiteSpace(o.GeneratedTsx) || !string.IsNullOrWhiteSpace(o.GeneratedHtml))
                .OrderByDescending(o => o.CreatedAt)
                .FirstOrDefault()
                ?? throw new Exception("No generated code found for this project. Please generate code first.");

            // Step 4: Build file list to push
            var files = new Dictionary<string, string>();

            if (!string.IsNullOrWhiteSpace(latest.GeneratedHtml))
                files["index.html"] = latest.GeneratedHtml;

            if (!string.IsNullOrWhiteSpace(latest.GeneratedTsx))
                files["src/App.tsx"] = latest.GeneratedTsx;

            // Add a basic package.json for React+Vite
            files["package.json"] = """
{
  "name": "ai-generated-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^4.4.0"
  }
}
""";

            files["README.md"] = $"""
# AI Generated App

This project was generated by [AI Code Gen](https://ai-code-gen.app).

## Getting Started

```bash
npm install
npm run dev
```

## Build

```bash
npm run build
```

> Generated on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC
""";

            // Step 5: Commit each file via GitHub Contents API
            int committed = 0;
            foreach (var (filePath, content) in files)
            {
                var base64Content = Convert.ToBase64String(Encoding.UTF8.GetBytes(content));

                // Check if file already exists to get SHA (required for updates)
                string? existingSha = null;
                var checkUrl = $"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}/contents/{filePath}?ref={dto.Branch}";
                var checkRes = await http.GetAsync(checkUrl);
                if (checkRes.IsSuccessStatusCode)
                {
                    var checkJson = JsonDocument.Parse(await checkRes.Content.ReadAsStringAsync()).RootElement;
                    if (checkJson.TryGetProperty("sha", out var shaEl))
                        existingSha = shaEl.GetString();
                }

                var bodyObj = new Dictionary<string, object?>
                {
                    ["message"] = $"{dto.CommitMessage} ({filePath})",
                    ["content"] = base64Content,
                    ["branch"] = dto.Branch
                };
                if (existingSha != null)
                    bodyObj["sha"] = existingSha;

                var putBody = JsonSerializer.Serialize(bodyObj);
                var putUrl = $"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}/contents/{filePath}";
                var putRes = await http.PutAsync(putUrl, new StringContent(putBody, Encoding.UTF8, "application/json"));

                if (!putRes.IsSuccessStatusCode)
                {
                    var errBody = await putRes.Content.ReadAsStringAsync();
                    // If branch not found, try creating it from default branch then retry
                    if (putRes.StatusCode == System.Net.HttpStatusCode.UnprocessableEntity
                        && errBody.Contains("branch", StringComparison.OrdinalIgnoreCase))
                    {
                        // Get default branch SHA
                        var repoInfoRes = await http.GetAsync($"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}");
                        if (repoInfoRes.IsSuccessStatusCode)
                        {
                            var repoJson = JsonDocument.Parse(await repoInfoRes.Content.ReadAsStringAsync()).RootElement;
                            var defaultBranch = repoJson.TryGetProperty("default_branch", out var db) ? db.GetString() : "main";
                            var refRes = await http.GetAsync($"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}/git/ref/heads/{defaultBranch}");
                            if (refRes.IsSuccessStatusCode)
                            {
                                var refJson = JsonDocument.Parse(await refRes.Content.ReadAsStringAsync()).RootElement;
                                var sha = refJson.GetProperty("object").GetProperty("sha").GetString();
                                var createBranchBody = JsonSerializer.Serialize(new { @ref = $"refs/heads/{dto.Branch}", sha });
                                await http.PostAsync(
                                    $"https://api.github.com/repos/{ownerLogin}/{dto.RepoName}/git/refs",
                                    new StringContent(createBranchBody, Encoding.UTF8, "application/json")
                                );
                                // Retry the put
                                putRes = await http.PutAsync(putUrl, new StringContent(putBody, Encoding.UTF8, "application/json"));
                            }
                        }
                    }
                    if (!putRes.IsSuccessStatusCode)
                        throw new Exception($"Failed to push file '{filePath}': {await putRes.Content.ReadAsStringAsync()}");
                }

                committed++;
            }

            return new PushResultDto
            {
                RepoUrl = $"https://github.com/{ownerLogin}/{dto.RepoName}",
                Branch = dto.Branch,
                FilesCommitted = committed,
                OwnerLogin = ownerLogin
            };
        }
    }
}
