
import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import authService, { UserDto } from '../../services/authService';
import githubService from '../../services/githubService';
import { GITHUB_CLIENT_ID, GITHUB_REDIRECT_URI } from '../../constants/githubConfig';

const GitHubIntegration: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const projectId = searchParams.get('projectId') ?? '';

  const [user, setUser] = useState<UserDto | null>(null);
  const [loading, setLoading] = useState(true);
  const [disconnecting, setDisconnecting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Form state
  const [repoName, setRepoName] = useState('ai-generator-student-project');
  const [branch, setBranch] = useState('main');
  const [commitMessage, setCommitMessage] = useState('Initial commit: Scaffolding generated by AI Frontend Generator');
  const [pushing, setPushing] = useState(false);

  const fetchUser = async () => {
    try {
      const res = await authService.getMe();
      setUser(res.data?.content ?? null);
    } catch {
      setError('Failed to load user info.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUser();
  }, []);

  const handleConnect = () => {
    const params = new URLSearchParams({
      client_id: GITHUB_CLIENT_ID,
      redirect_uri: GITHUB_REDIRECT_URI,
      scope: 'repo user:email',
      state: 'github-integration',
    });
    window.location.href = `https://github.com/login/oauth/authorize?${params.toString()}`;
  };

  const handleDisconnect = async () => {
    if (!window.confirm('Are you sure you want to disconnect your GitHub account?')) return;
    setDisconnecting(true);
    setError(null);
    try {
      await authService.disconnectGitHub();
      await fetchUser();
    } catch (e: unknown) {
      const msg = (e as { response?: { data?: { message?: string } } })?.response?.data?.message;
      setError(msg ?? 'Failed to disconnect GitHub account.');
    } finally {
      setDisconnecting(false);
    }
  };

  const handlePush = async () => {
    if (!projectId) {
      setError('No project selected. Please open the editor first and click "Push to GitHub" from there.');
      return;
    }
    if (!repoName.trim()) {
      setError('Repository name is required.');
      return;
    }
    setPushing(true);
    setError(null);
    try {
      const res = await githubService.push({
        projectId,
        repoName: repoName.trim(),
        branch,
        commitMessage: commitMessage.trim() || 'Code push from AI Generator',
      });
      const result = res.data?.content;
      navigate('/github-status', {
        state: {
          repoUrl: result?.repoUrl,
          branch: result?.branch,
          filesCommitted: result?.filesCommitted,
          ownerLogin: result?.ownerLogin,
        },
      });
    } catch (e: unknown) {
      const msg = (e as { response?: { data?: { message?: string } } })?.response?.data?.message;
      setError(msg ?? 'Failed to push code to GitHub. Please try again.');
    } finally {
      setPushing(false);
    }
  };

  const isConnected = !!user?.gitHubId;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 font-display">
      <main className="flex flex-col max-w-[800px] mx-auto flex-1 gap-6">
        <div className="flex flex-wrap justify-between gap-3">
          <div className="flex min-w-72 flex-col gap-2">
            <p className="text-slate-900 dark:text-white text-4xl font-black leading-tight tracking-[-0.033em]">GitHub Integration</p>
            <p className="text-slate-600 dark:text-[#9da6b9] text-base font-normal">Connect your project to a remote repository to automate deployments and version control.</p>
          </div>
        </div>

        {error && (
          <div className="rounded-lg bg-red-500/10 border border-red-500/30 px-4 py-3 text-red-400 text-sm">{error}</div>
        )}

        <div className="px-0">
          <div className="flex items-center justify-between gap-6 rounded-xl bg-white dark:bg-[#1c1f27] p-6 border border-slate-200 dark:border-[#282e39] shadow-lg">
            {loading ? (
              <div className="flex items-center gap-3 text-slate-500 dark:text-[#9da6b9] text-sm animate-pulse">
                <span className="material-symbols-outlined text-[24px]">hourglass_empty</span>
                Loading GitHub status…
              </div>
            ) : isConnected ? (
              <>
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-primary/10 rounded-lg">
                    {user?.avatarUrl
                      ? <img src={user.avatarUrl} alt="avatar" className="w-8 h-8 rounded-full" />
                      : <span className="material-symbols-outlined text-primary text-[32px]">account_circle</span>
                    }
                  </div>
                  <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2">
                      <p className="text-slate-900 dark:text-white text-lg font-bold leading-tight">
                        Connected as {user?.name ? `@${user.name}` : user?.email}
                      </p>
                      <span className="px-2 py-0.5 rounded-full bg-green-500/20 text-green-400 text-[10px] font-bold uppercase tracking-wider border border-green-500/30">Active</span>
                    </div>
                    <p className="text-slate-500 dark:text-[#9da6b9] text-sm font-normal">GitHub ID: {user?.gitHubId}</p>
                  </div>
                </div>
                <button
                  onClick={handleDisconnect}
                  disabled={disconnecting}
                  className="flex min-w-[84px] cursor-pointer items-center justify-center rounded-lg h-10 px-4 bg-slate-100 dark:bg-[#282e39] hover:bg-red-500/10 hover:border-red-500/40 hover:text-red-400 text-slate-900 dark:text-white gap-2 text-sm font-medium transition-all border border-slate-200 dark:border-[#3b4354] disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <span className="material-symbols-outlined text-[18px]">link_off</span>
                  <span className="truncate">{disconnecting ? 'Disconnecting…' : 'Disconnect'}</span>
                </button>
              </>
            ) : (
              <>
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-slate-100 dark:bg-[#282e39] rounded-lg">
                    <span className="material-symbols-outlined text-slate-400 text-[32px]">link_off</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <p className="text-slate-900 dark:text-white text-lg font-bold leading-tight">Not connected</p>
                    <p className="text-slate-500 dark:text-[#9da6b9] text-sm font-normal">Connect your GitHub account to enable push functionality.</p>
                  </div>
                </div>
                <button
                  onClick={handleConnect}
                  className="flex min-w-[84px] cursor-pointer items-center justify-center rounded-lg h-10 px-4 bg-primary hover:bg-primary/90 text-white gap-2 text-sm font-medium transition-all"
                >
                  <span className="material-symbols-outlined text-[18px]">add_link</span>
                  <span className="truncate">Connect</span>
                </button>
              </>
            )}
          </div>
        </div>

        <div className="pt-4">
          <h2 className="text-slate-900 dark:text-white text-[22px] font-bold leading-tight tracking-[-0.015em]">Repository Configuration</h2>
          <div className="mt-1">
            <div className="h-1 w-12 bg-primary rounded-full"></div>
          </div>
        </div>

        <div className="flex flex-col gap-4 py-2">
          <div className="flex flex-col gap-2">
            <label className="flex flex-col flex-1">
              <p className="text-slate-700 dark:text-white text-sm font-medium leading-normal pb-2">
                Repository Name <span className="text-red-400">*</span>
              </p>
              <div className="flex w-full items-stretch rounded-lg shadow-sm">
                <input
                  className="form-input flex w-full min-w-0 flex-1 rounded-lg text-slate-900 dark:text-white focus:outline-0 focus:ring-1 focus:ring-primary border border-slate-200 dark:border-[#3b4354] bg-white dark:bg-[#1c1f27] focus:border-primary h-14 placeholder:text-slate-400 dark:placeholder:text-[#4d576e] p-[15px] rounded-r-none border-r-0 pr-2 text-base font-normal"
                  placeholder="my-awesome-frontend-app"
                  value={repoName}
                  onChange={(e) => setRepoName(e.target.value)}
                />
                <div className="text-slate-400 dark:text-[#9da6b9] flex border border-slate-200 dark:border-[#3b4354] bg-slate-50 dark:bg-[#1c1f27] items-center justify-center pr-[15px] rounded-r-lg border-l-0">
                  <span className="material-symbols-outlined">account_tree</span>
                </div>
              </div>
            </label>
            <p className="text-slate-500 dark:text-[#5d6a85] text-xs">A new public repository will be created if it doesn't exist.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <label className="flex flex-col flex-1">
              <p className="text-slate-700 dark:text-white text-sm font-medium leading-normal pb-2">Frontend Framework</p>
              <div className="flex w-full items-stretch rounded-lg opacity-80 cursor-not-allowed">
                <div className="flex w-full min-w-0 flex-1 items-center rounded-lg text-slate-600 dark:text-white border border-slate-200 dark:border-[#3b4354] bg-slate-100 dark:bg-[#161921] h-14 px-[15px] rounded-r-none border-r-0 pr-2 text-base font-normal">
                  React (Vite)
                </div>
                <div className="text-slate-400 dark:text-[#9da6b9] flex border border-slate-200 dark:border-[#3b4354] bg-slate-100 dark:bg-[#161921] items-center justify-center pr-[15px] rounded-r-lg border-l-0">
                  <span className="material-symbols-outlined">inventory_2</span>
                </div>
              </div>
            </label>
            <label className="flex flex-col flex-1">
              <p className="text-slate-700 dark:text-white text-sm font-medium leading-normal pb-2">Target Branch</p>
              <div className="flex w-full items-stretch rounded-lg">
                <select
                  className="form-select flex w-full min-w-0 flex-1 rounded-lg text-slate-900 dark:text-white focus:outline-0 focus:ring-1 focus:ring-primary border border-slate-200 dark:border-[#3b4354] bg-white dark:bg-[#1c1f27] focus:border-primary h-14 px-[15px] text-base font-normal appearance-none"
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                >
                  <option value="main">main</option>
                  <option value="develop">develop</option>
                  <option value="staging">staging</option>
                </select>
              </div>
            </label>
          </div>

          <label className="flex flex-col flex-1">
            <p className="text-slate-700 dark:text-white text-sm font-medium leading-normal pb-2">Commit Message</p>
            <div className="flex w-full items-stretch rounded-lg">
              <textarea
                className="form-textarea flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-lg text-slate-900 dark:text-white focus:outline-0 focus:ring-1 focus:ring-primary border border-slate-200 dark:border-[#3b4354] bg-white dark:bg-[#1c1f27] focus:border-primary min-h-[80px] placeholder:text-slate-400 dark:placeholder:text-[#4d576e] p-[15px] text-base font-normal"
                placeholder="Describe your changes..."
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
              />
            </div>
          </label>
        </div>

        <div className="py-6 border-t border-slate-200 dark:border-[#282e39] mt-4">
          {!isConnected ? (
            <button
              disabled
              className="w-full flex items-center justify-center rounded-xl h-16 px-6 bg-slate-300 dark:bg-[#282e39] text-slate-500 dark:text-slate-500 gap-3 text-lg font-bold cursor-not-allowed"
            >
              <span className="material-symbols-outlined">cloud_upload</span>
              <span>Connect GitHub first</span>
            </button>
          ) : !projectId ? (
            <button
              disabled
              className="w-full flex items-center justify-center rounded-xl h-16 px-6 bg-slate-300 dark:bg-[#282e39] text-slate-500 dark:text-slate-500 gap-3 text-lg font-bold cursor-not-allowed"
            >
              <span className="material-symbols-outlined">cloud_upload</span>
              <span>Open from Editor to push a project</span>
            </button>
          ) : (
            <button
              onClick={handlePush}
              disabled={pushing}
              className="w-full flex cursor-pointer items-center justify-center rounded-xl h-16 px-6 bg-primary hover:bg-primary/90 text-white gap-3 text-lg font-bold transition-all shadow-[0_0_20px_rgba(19,91,236,0.3)] group disabled:opacity-70 disabled:cursor-not-allowed"
            >
              {pushing ? (
                <>
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Pushing to GitHub…</span>
                </>
              ) : (
                <>
                  <span className="material-symbols-outlined group-hover:translate-x-1 transition-transform">cloud_upload</span>
                  <span>Push Code to GitHub</span>
                </>
              )}
            </button>
          )}
          <p className="text-center text-slate-500 dark:text-[#5d6a85] text-sm mt-4">
            By clicking, you agree to create a repository and push the generated source code to your GitHub account.
          </p>
        </div>

        <div className="pb-10">
          <div className="rounded-lg border border-slate-200 dark:border-[#282e39] bg-[#0d1117] overflow-hidden">
            <div className="bg-slate-50 dark:bg-[#1c2128] px-4 py-2 border-b border-slate-200 dark:border-[#282e39] flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="size-3 rounded-full bg-[#ff5f56]"></div>
                <div className="size-3 rounded-full bg-[#ffbd2e]"></div>
                <div className="size-3 rounded-full bg-[#27c93f]"></div>
                <span className="ml-4 text-xs text-slate-500 dark:text-[#9da6b9] font-mono">deployment_preview.sh</span>
              </div>
            </div>
            <div className="p-6 font-mono text-xs text-green-400 leading-relaxed">
              <p><span className="text-blue-400">git</span> init</p>
              <p><span className="text-blue-400">git</span> add .</p>
              <p><span className="text-blue-400">git</span> commit -m "{commitMessage || 'Initial commit from AI Generator'}"</p>
              <p><span className="text-blue-400">git</span> remote add origin https://github.com/&#123;user&#125;/{repoName || 'my-repo'}.git</p>
              <p><span className="text-blue-400">git</span> push -u origin {branch}</p>
              <p className="text-white mt-2 animate-pulse">_</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default GitHubIntegration;

